### ISSUE TITLE
Djinn 

### ISSUE THREAD

**Issue by knkrth** [jhauswald/lucida#2]
Hi, are you working on djinn to integrate with lucida? can you explain me how to link djinn with lucida?

**Comment by jhauswald** [comment]
Yes! We are currently working on this @haoyifan could you post your updates/progress?

**Comment by haoyifan** [comment]
I'm still trying to set up djinn in my machine. There are a lot more dependency libraries and prerequisites than I expected(nvcc, BLAS, openCV, hdf5 etc.) Currently I'm reinstalling BLAS libraries since the compilation of caffe will terminate without certain BLAS libraries. I'll let you know when I make more progress.

**Comment by haoyifan** [comment]
Hi Johann. I just install djinn in my linux successfully. My PC broke down when I tried to install BLAS. But I finally get the executable in my service directory. I think you need to add some instructions on setting up the dependencies. I had tons of dependency errors even if I installed all of the libraries correctly. The users need to modify some bash file and export several environment variables to let the compiler know where to find the right libraries.

However, when I tried to run djinn as a server, it says segmentation fault. Have you encountered such problem before?

**Comment by knkrth** [comment]
I'm closing this because this issue is not related to this project. This issue can be carried out on  <a href="https://github.com/claritylab/djinn/issues/2">#2</a>
